name: qupath
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-image=0.19.3
  - pip
  - pip:
    - paquo==0.6.1
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - python-multipart==0.0.6
